name: PR Check

on:
  pull_request:
    branches: [ "**" ]

jobs:
  spotless:
    name: Code Style Spotless Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run spotless plugin check
        run: ./mvnw spotless:check

  verify:
    name: Maven Build & Test
    needs: spotless
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run mvn verify
        run: ./mvnw verify
